### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by christophrumpel** [boxybird/laravel-directus-api-wrapper#1]
Hey,

thanks for this package. Are you planning to support Laravel 8 too?
Greets

**Comment by boxybird** [comment]
Hello! 

I see no reason not to. Going through the Laravel 8 release notes, there doesn't appear to be any real challenges upgrading the package. 

Give me sometime to look things over.

**Comment by christophrumpel** [comment]
Hey, yeah cool. No worries, take your time. 👍

**Comment by doughnet** [comment]
Awesome I just found this. Can't wait to try it in laravel 8!

**Comment by boxybird** [comment]
Added support for Laravel 8.
