### ISSUE TITLE
Complete example component/view usage

### ISSUE THREAD

**Issue by doughnet** [boxybird/laravel-directus-api-wrapper#2]
Hi. First off thanks for your work on the project. Definitely makes it easy to use. I'm VERY new to using laravel and was wondering if you had a functional front end coded already. I keep getting an issue with foreach usage on a list of items. I know the data is being pulled since I can do a var_dump($items); and get the full array.

Also is there a way to avoid have to ['data'] array and have it go straight to the actual array data?

**Comment by boxybird** [comment]
Hey @doughnet! I don't have a frontend I can show, but here are a few examples that may help.

**Example 1:** Looping with `['data']`.
```php
// web.php
Route::get('/', function () {
    $jokes = Api::request('GET', '/items/dad_jokes');

    return view('welcome', [
        'jokes' => $jokes,
    ]);
});

// welcome.blade.php
<ul>
    @foreach ($jokes['data'] as $joke)
        <li>{{ $joke['title'] }}</li>
    @endforeach
</ul>
```

**Example 2:** "Also is there a way to avoid have to ['data']..." - Prepare array before passing to the `view()`.
```php
// web.php
Route::get('/', function () {
    $jokes = Api::request('GET', '/items/dad_jokes');

    // Using https://laravel.com/docs/8.x/collections
    $jokes = collect($jokes['data']);

    return view('welcome', [
        'jokes' => $jokes,
    ]);
});

// welcome.blade.php
<ul>
    @foreach ($jokes as $joke)
        <li>{{ $joke['title'] }}</li>
    @endforeach
</ul>
```

**Comment by doughnet** [comment]
Thank you. I'll give that a go.

**Comment by doughnet** [comment]
That worked out great; thanks!  One comment; wouldn't it be easier to just have the ['data'] hardcoded (I assume it's across the board for all the API calls?).

**Comment by boxybird** [comment]
Possibly, but that would be up to Directus. 

This package simply returns the raw API payload from Dirtectus with no structural manipulation. The benefit is you can reference their docs to see the response format for all the endpoints. https://docs.directus.io/api/reference.html

Naturally, in Laravel you'll see a returned PHP array vs a JSON object, but it is a mirror image.

**Comment by doughnet** [comment]
Do you have a recommendation where to include the authentication information to have it access across all laravel?

**Comment by boxybird** [comment]
This will do the trick: https://github.com/boxybird/laravel-directus-api-wrapper#authentication-httpsdocsdirectusioapiauthenticationhtml

**Comment by boxybird** [comment]
Looks like you found a path forward. Closing this for now.
