### ISSUE TITLE
User cached to same key

### ISSUE THREAD

**Issue by christophrumpel** [boxybird/laravel-directus-api-wrapper#3]
Hey,

I was checking the example for Authentication a directus user and I'm not sure if I got that right.
It seems that a user gets always cached with the same key `directus_auth_user` in the cache.

- Key https://github.com/boxybird/laravel-directus-api-wrapper/blob/master/src/Directus/Directus.php#L15
- Caching the user https://github.com/boxybird/laravel-directus-api-wrapper/blob/master/src/Directus/Directus.php#L15

Shouldn't the key be set to a unique session-id? Because currently, every user from every browser session has access to the cached user if you just run `Directus::getUser()`.

**Comment by boxybird** [comment]
Hello, 

Interesting. I'm not sure I built this package for your use case in mind (assuming I understand you correctly).

And it looks like `directus_auth_user` and `Directus::getUser()` may have been poor word choices on my part. 

My goal with the package was to allow Laravel to connect to a headless Directus install as if it was simply another database connection. Think MYSQL config: You need to provide a username, password, host, port, etc. Those values never change. Same here.

Sounds like you want to authenticate individual users of your Directus install (https://docs.directus.io/api/users.html) on a per session bases?  

If so, it should be possible. You could use and store its value:
```php
Route::get('/login', function () {
    $auth = Auth::authenticate([
        'email'    => 'another-directus-user@gmail.com',
        'password' => '12345678'
    ]);

    // Handle $auth response however you want (i.e. store in session)
    session()->put('current_user', $auth);

    // ...
});
```
All this said, I see where you're coming from and think a few refactors are needed. 

And this section is indeed confusing: https://github.com/boxybird/laravel-directus-api-wrapper#authentication-httpsdocsdirectusioapiauthenticationhtml

Thanks for the insight!

**Comment by christophrumpel** [comment]
Hey, thanks for the fast response. I get now how it was meant in the docs. And you are right, in our Laravel application, we let users from Directus login in. Yeah I'll use the session now to make the connection to a specific user. Thanks 👍

**Comment by boxybird** [comment]
@christophrumpel I left out an important detail...

If you need to manually add a JWT per request, you can pass it as an arg. 

```php
Route::get('/show-me-data', function () {
    $current_user =  session()->get('current_user'); 

    $jwt = data_get($current_user, 'data.token');

    // Assuming '/items/posts' is a protected endpoint
    $posts = $Api::request('GET', '/items/posts', [], $jwt);

    // ....
});
```
https://github.com/boxybird/laravel-directus-api-wrapper/blob/master/src/Directus/Api/Api.php#L9

**Comment by christophrumpel** [comment]
Hey, I just came back to write about the JWT token 😅 I just noticed the wrapper is calling it from the cache in the back.

Which was causing some weird issues. It's great that we can add it manually, this should fix my issues. Thanks.
